# Antigen (ZSH package manager) configuration
source ~/.antigen.zsh
antigen use oh-my-zsh

antigen bundle git
antigen bundle tmux
antigen bundle lein
antigen bundle pip
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen apply

# # Tools configuration
# ## AutoJump
source /usr/share/autojump/autojump.zsh

# Aliases
alias ls='ls --color'
# TMux aliases
alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'
# Generic
alias open='open_command'
# Emacs
alias killemacs='emacsclient -e "(kill-emacs)"'
alias e='emacsclient -nw --alternate-editor="" --create-frame "$@"'
alias E='emacsclient --alternate-editor="" --create-frame "$@" --no-wait --quiet'

# Environment Variables
export SHELL=/usr/bin/zsh
export EDITOR=vim

# source ~/.zshrc.vars
# source ~/.zshrc.exo

# added by pipsi (https://github.com/mitsuhiko/pipsi)
export PATH="/home/bertrand/.local/bin:$PATH"

# BEGIN ANSIBLE MANAGED BLOCK
export GOPATH=$HOME/Workspace/Go
export PATH=$PATH:$GOPATH/bin
# END ANSIBLE MANAGED BLOCK
