- name: ZSH
  apt:
    name: ['silversearcher-ag', 'tmux', 'autojump', 'zsh', 'zsh-completions']
    state: present
  become: true

- name: Download Tmux configuration
  get_url:
    url: https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf
    dest: /home/{{ user.name }}/.tmux.conf
