- name: Install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: /home/{{ user.name }}/.emacs.d
    version: develop

# https://www.masteringemacs.org/article/keeping-secrets-in-emacs-gnupg-auth-sources
