- name: Install development tools
  pacman: name={{ item }} state=present
  with_items:
    - jq
  become: true

- include: git.yml
- include: vim.yml
- include: spacemacs.yml
- include: jetbrains.yml
- include: clojure.yml

