- name: Install development tools
  apt:
    name: ['jq', 'terminator', 'xsel', 'tree']
    state: present
  become: true

- name: Install AWS
  shell: pipsi install awscli
  register: command_result
  failed_when: command_result.rc != 0 and 'is already installed' not in command_result.stdout

