- name:    Install Docker
  apt: 
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present
  become: true

- name:    Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name:    Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  become: true

- name:    Install Docker
  apt:
    name: docker-ce
    state: present
  become: true

- name:    Add {{ user.name }} to Docker group
  user:
    name: "{{ user.name }}"
    groups: "docker"
    append: true
  become: true

- name:    Platform version
  command: uname -s
  register: plat_version

- name:    Arch version
  command: uname -m
  register: arch_version

- name:    Install docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-{{ plat_version.stdout }}-{{ arch_version.stdout }}"
    dest: /home/{{ user.name }}/.local/bin/docker-compose
    mode: +x

- name: Install local registry
  file:
    path: /etc/docker/certs.d/registry.internal.exoscale.ch
    state: directory
  become: true

- name: Copy certificate authority
  copy:
    content: "{{ item.content }}"
    dest: "/etc/docker/certs.d/registry.internal.exoscale.ch/{{ item.path }}"
    mode: 0600
  become: true
  with_items:
    - { content: "{{ exo_ca_cert }}", path: ca.crt }
    - { content: "{{ docker_client_cert }}", path: client.cert }
    - { content: "{{ docker_client_key }}", path: client.key }


